name: Deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:
  rabota:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Hello_world_application docker
      run: |
        sudo docker volume create my_data
        sudo docker build -t docker-hello .
        sudo docker run docker-hello
      #  sudo docker run -d -v my_data:/data docker-hello
       

     # Output build artifacts to /github/workspace on the container.
    # - name: Containerized Build
    #   uses: ./.github/actions/docker-hello

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: workspace_artifacts
        path: ${{ github.workspace }}/build/Hello_world_application/main

  create_release:
    needs: rabota
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: download_workspace_artifacts
      uses: actions/download-artifact@v4
      with:
        name: workspace_artifacts
        path: ${{ github.workspace }}

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v1.${{ github.run_number }}
        name: Release v1.${{ github.run_number }}  
        files: |
          main  