name: Deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:
  rabota:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Hello_world_application docker
      run: |
        sudo docker build -t docker-hello .
        sudo docker run docker-hello